### ISSUE TITLE
Minutes of latest general meeting + committee update

### ISSUE THREAD

**Issue by keithpitty** [rubyaustralia/ruby.org.au#42]
@pat @vonconrad sorry to hit you up so soon after your sterling work for the conference but perhaps you can delegate to someone on the committee to:
* add the minutes of the general meeting held at Rails Camp 16
* update the committee page

**Comment by pat** [comment]
No worries Keith - good to have this on the radar. @mikel do you have the minutes? Or did someone else record them?

**Comment by vonconrad** [comment]
Mel Sherrin took minutes at the GM.

**Comment by msherrin** [comment]
Sent them to Matt. Fresh copy at you in a sec.

**Comment by pat** [comment]
Thanks all. Site's now updated with minutes and committee changes. @mikel: just missing a bio from you :)
